# Generated by Django 5.0.6 on 2024-08-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roombooking', '0003_customer_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('Done', 'Done'), ('Progress', 'Progress')], default='Progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('in-progress', 'in-progress')], default='Confirmed', max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Single BedRoom', 'Single BedRoom'), ('Double BedRoom', 'Double Bedroom')], max_length=50),
        ),
    ]
