# Generated by Django 5.0.6 on 2024-08-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roombooking', '0004_payment_payment_status_alter_booking_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
